# Generated by Django 6.1 on 2026-09-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news_post',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
